apiVersion: ecr.aws.upbound.io/v1beta1
kind: RepositoryPolicy
metadata:
  name: crossplane-blanketops-ecr-repository-policy
spec:
  forProvider:
    policy: |
      {
          "Version": "2008-10-17",
          "Statement": [
              {
                  "Sid": "new policy",
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": [
                      "ecr:GetDownloadUrlForLayer",
                      "ecr:BatchGetImage",
                      "ecr:BatchCheckLayerAvailability",
                      "ecr:PutImage",
                      "ecr:InitiateLayerUpload",
                      "ecr:UploadLayerPart",
                      "ecr:CompleteLayerUpload",
                      "ecr:DescribeRepositories",
                      "ecr:GetRepositoryPolicy",
                      "ecr:ListImages",
                      "ecr:DeleteRepository",
                      "ecr:BatchDeleteImage",
                      "ecr:SetRepositoryPolicy",
                      "ecr:DeleteRepositoryPolicy"
                  ]
              }
          ]
      }
    region: eu-north-1
    repository: crossplane-blanketops-ecr-repository
  providerConfigRef:
    name: default
