apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  name: crossplane-blanketops-argo-application
spec:
  forProvider:
    destination:
      namespace: default
      server: https://kubernetes.default.svc
    project: default
    source:
      path: charts/blanketops-nginx-example
      repoURL: https://github.com/stefanprodan/podinfo/
      targetRevision: HEAD
  providerConfigRef:
    name: argocd-provider
