apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ec2/v1beta1/defaultroutetable
  labels:
    testing.upbound.io/example-name: example
  name: sample-vpc
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: eu-north-1
    tags:
      Name: DemoVpc
