apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: Notification
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta1/notification
  labels:
    testing.upbound.io/example-name: example_notifications
  name: example-notifications
spec:
  forProvider:
    groupNames:
    - bar
    - foo
    notifications:
    - autoscaling:EC2_INSTANCE_LAUNCH
    - autoscaling:EC2_INSTANCE_TERMINATE
    - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
    - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
    region: us-west-1
    topicArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
