apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: LifecycleHook
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta1/lifecyclehook
  labels:
    testing.upbound.io/example-name: blanketopsautoscaling
  name: blanketops-autoscaling-lifecyclehook
spec:
  forProvider:
    autoscalingGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    defaultResult: CONTINUE
    heartbeatTimeout: 2000
    lifecycleTransition: autoscaling:EC2_INSTANCE_LAUNCHING
    notificationMetadata: |
      {
        "foo": "bar"
      }
    region: eu-north-1
