apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: Schedule
metadata:
  annotations:
    meta.upbound.io/example-id: autoscaling/v1beta1/schedule
  labels:
    testing.upbound.io/example-name: blanketops-autoscaling-schedule-example
  name: blanketops-autoscaling-schedule-example
spec:
  forProvider:
    autoscalingGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: blanketops-autoscaling-schedule-example
    desiredCapacity: 0
    endTime: 2023-12-12T06:00:00Z
    maxSize: 1
    minSize: 0
    region: eu-north-1
    startTime: 2023-12-11T18:00:00Z
